// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "./gen-cpp/ComputeNode.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::distributedML;

class ComputeNodeHandler : virtual public ComputeNodeIf {
 public:
  ComputeNodeHandler() {
    // Your initialization goes here
  }

  void trainModel(Gradient& _return, const Weights& weights, const std::string& trainFile, const double eta, const int32_t epochs) {
    cout << "Compute Node training " << tranFile << endl;
    mlp local_model;

    vector<vector<double>> W = weights.W;
    vector<vector<double>> V = weights.V;
    vector<vector<double>> W_original = W;
    vector<vector<double>> V_original = V;
    local_model.init_training_model(trainFile, V, W);

    double error = local_model.train(eta, epochs);

    local_model.get_weights(W, V);
    calc_gradient(W, W_original);
    calc_gradient(V, V_original);

    _return.dV = V;
    _return.dW = W;
  }

};

int main(int argc, char **argv) {
  if (argc != 3) {
    cerr << "Usage: ./compute_node <port> <load_probability>" << endl;
    return 1;
  }

  int port = stoi(argv[1]);
  double load_probability = stod(argv[2]);
  srand(time(NULL));
  ::std::shared_ptr<ComputeNodeHandler> handler(new ComputeNodeHandler());
  ::std::shared_ptr<TProcessor> processor(new ComputeNodeProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}
